var CurrencyCodeInfo = {
	aed: {name: "UAE Dirham", symbol: "د.إ"},   
    afn: {name: "Afghani", symbol: "؋"},   
    all: {name: "Lek", symbol: "Lek"},   
    amd: {name: "Armenian Dram", symbol: "Դ"},   
    ang: {name: "Netherlands Antillian Guilder", symbol: "ƒ"},   
    aoa: {name: "Kwanza", symbol: "Kz"},   
    ars: {name: "Argentine Peso", symbol: "$"},   
    aud: {name: "Australian Dollar", symbol: "$", country: "au"},   
    awg: {name: "Aruban Guilder", symbol: "ƒ"},   
    azn: {name: "Azerbaijanian Manat", symbol: "ман"},   
    bam: {name: "Convertible Marks", symbol: "KM"},   
    bbd: {name: "Barbados Dollar", symbol: "$"},   
    bdt: {name: "Taka", symbol: "৳"},   
    bgn: {name: "Bulgarian Lev", symbol: "лв"},   
    bhd: {name: "Bahraini Dinar", symbol: "ب.د"},   
    bif: {name: "Burundi Franc", symbol: "FBu"},   
    bmd: {name: "Bermudian Dollar", symbol: "$"},   
    bnd: {name: "Brunei Dollar", symbol: "$"},   
    bob: {name: "Boliviano", symbol: "$b"},   
    bov: {name: "Mvdol", symbol: "BOV"},   
    brl: {name: "Brazilian Real", symbol: "R$"},   
    bsd: {name: "Bahamian Dollar", symbol: "$"},   
    btn: {name: "Ngultrum", symbol: "Nu."},   
    bwp: {name: "Pula", symbol: "P"},   
    byr: {name: "Belarussian Ruble", symbol: "p."},   
    bzd: {name: "Belize Dollar", symbol: "BZ$"},   
    cad: {name: "Canadian Dollar", symbol: "$"},   
    cdf: {name: "Congolese Franc", symbol: "FC"},   
    che: {name: "WIR Euro", symbol: "CHE"},   
    chf: {name: "Swiss Franc", country: "ch", symbol: "Fr"},   
    chw: {name: "WIR Franc", symbol: "CHW"},   
    clf: {name: "Unidades de fomento", symbol: "UF"},   
    clp: {name: "Chilean Peso", symbol: "$"},   
    cny: {name: "Yuan Renminbi", symbol: "¥"},   
    cop: {name: "Colombian Peso", symbol: "$"},   
    cou: {name: "Unidad de Valor Real", symbol: "COU"},   
    crc: {name: "Costa Rican Colon", symbol: "₡"},   
    cuc: {name: "Peso Convertible", symbol: "$"},   
    cup: {name: "Cuban Peso", symbol: "₱"},   
    cve: {name: "Cape Verde Escudo", symbol: "$"},   
    czk: {name: "Czech Koruna", symbol: "Kč"},   
    djf: {name: "Djibouti Franc", symbol: "Fdj"},   
    dkk: {name: "Danish Krone", symbol: "kr", country: "dk"},   
    dop: {name: "Dominican Peso", symbol: "RD$"},   
    dzd: {name: "Algerian Dinar", symbol: "دج"},   
    eek: {name: "Kroon", symbol: "KR"},   
    egp: {name: "Egyptian Pound", symbol: "£"},   
    ern: {name: "Nakfa", symbol: "Nfk"},   
    etb: {name: "Ethiopian Birr", symbol: "Br"},   
    eur: {name: "Euro", symbol: "€", country: "eu"},   
    fjd: {name: "Fiji Dollar", symbol: "$"},   
    fkp: {name: "Falkland Islands Pound", symbol: "£"},   
    gbp: {name: "Pound Sterling", symbol: "£", country: "gb"},   
    gel: {name: "Lari", symbol: "ლ"}, 
	ggp: {name: "GGP", symbol: "£"},   
    ghc: {name: "Ghanaian cedi", symbol: "¢"},   
    ghs: {name: "Cedi", symbol: "GH₵"},   
    gip: {name: "Gibraltar Pound", symbol: "£"},   
    gmd: {name: "Dalasi", symbol: "D"},   
    gnf: {name: "Guinea Franc", symbol: "FG"},   
    gtq: {name: "Quetzal", symbol: "Q"},   
    gyd: {name: "Guyana Dollar", symbol: "$"},   
    hkd: {name: "Hong Kong Dollar", symbol: "$"},   
    hnl: {name: "Lempira", symbol: "L"},   
    hrk: {name: "Croatian Kuna", symbol: "kn"},   
    htg: {name: "Gourde", symbol: "G"},   
    huf: {name: "Forint", symbol: "Ft"},   
    idr: {name: "Rupiah", symbol: "Rp"},   
    ils: {name: "New Israeli Sheqel", symbol: "₪"},   
    imp: {name: "IMP", symbol: "£"},   
    inr: {name: "Indian Rupee", country: "in",symbol: "&#8377;"},   
    iqd: {name: "Iraqi Dinar", symbol: "ع.د"},   
    irr: {name: "Iranian Rial", symbol: "﷼"},   
    isk: {name: "Iceland Krona", symbol: "kr"},   
    jep: {name: "JEP", symbol: "£"},   
    jmd: {name: "Jamaican Dollar", symbol: "J$"},   
    jod: {name: "Jordanian Dinar", symbol: "د.ا"},   
    jpy: {name: "Yen", symbol: "¥"},   
    kes: {name: "Kenyan Shilling", symbol: "KSh"},   
    kgs: {name: "Som", symbol: "лв"},   
    khr: {name: "Riel", symbol: "៛"},   
    kmf: {name: "Comoro Franc", symbol: "CF"},   
    kpw: {name: "North Korean Won", symbol: "₩"},   
    krw: {name: "Won", symbol: "₩"},   
    kwd: {name: "Kuwaiti Dinar", symbol: "K.D."},   
    kyd: {name: "Cayman Islands Dollar", symbol: "$"},   
    kzt: {name: "Tenge", symbol: "лв"},   
    lak: {name: "Kip", symbol: "₭"},   
    lbp: {name: "Lebanese Pound", symbol: "£"},   
    lkr: {name: "Sri Lanka Rupee", symbol: "₨"},   
    lrd: {name: "Liberian Dollar", symbol: "$"},   
    lsl: {name: "Loti", symbol: "L"},   
    ltl: {name: "Lithuanian Litas", symbol: "Lt"},   
    lvl: {name: "Latvian Lats", symbol: "Ls"},   
    lyd: {name: "Libyan Dinar", symbol: "LD"},   
    mad: {name: "Moroccan Dirham", symbol: "م.", country: "ma"},   
    mdl: {name: "Moldovan Leu", symbol: "L"},   
    mga: {name: "Malagasy Ariary", symbol: "Ar"},   
    mkd: {name: "Denar", symbol: "ден"},   
    mmk: {name: "Kyat", symbol: "K"},   
    mnt: {name: "Tugrik", symbol: "₮"},   
    mop: {name: "Pataca", symbol: "MOP$"},   
    mro: {name: "Ouguiya", symbol: "UM"},   
    mur: {name: "Mauritius Rupee", symbol: "₨"},   
    mvr: {name: "Rufiyaa", symbol: "Rf"},   
    mwk: {name: "Kwacha", symbol: "MK"},   
    mxn: {name: "Mexican Peso", symbol: "$"},   
    mxv: {name: "Mexican Unidad de Inversion (UDI}", symbol: "MXV"},   
    myr: {name: "Malaysian Ringgit", symbol: "RM"},   
    mzn: {name: "Metical", symbol: "MT"},   
    nad: {name: "Namibia Dollar", symbol: "$"},   
    ngn: {name: "Naira", symbol: "₦"},   
    nio: {name: "Cordoba Oro", symbol: "C$"},   
    nok: {name: "Norwegian Krone", symbol: "kr", country: "no"},   
    npr: {name: "Nepalese Rupee", symbol: "₨"},   
    nzd: {name: "New Zealand Dollar", symbol: "$", country: "nz"},   
    omr: {name: "Rial Omani", symbol: "﷼"},   
    pab: {name: "Balboa", symbol: "B/."},   
    pen: {name: "Nuevo Sol", symbol: "S/."},   
    pgk: {name: "Kina", symbol: "K"},   
    php: {name: "Philippine Peso", symbol: "Php"},   
    pkr: {name: "Pakistan Rupee", symbol: "₨"},   
    pln: {name: "Zloty", symbol: "zł"},   
    pyg: {name: "Guarani", symbol: "Gs"},   
    qar: {name: "Qatari Rial", symbol: "﷼"},   
    ron: {name: "New Leu", symbol: "lei"},   
    rsd: {name: "Serbian Dinar", symbol: "Дин."},   
    rub: {name: "Russian Ruble", symbol: "руб"},   
    rwf: {name: "Rwanda Franc", symbol: "FRw"},   
    sar: {name: "Saudi Riyal", symbol: "﷼"},   
    sbd: {name: "Solomon Islands Dollar", symbol: "$"},   
    scr: {name: "Seychelles Rupee", symbol: "₨"},   
    sdg: {name: "Sudanese Pound", symbol: "sdg"},   
    sek: {name: "Swedish Krona", symbol: "kr"},   
    sgd: {name: "Singapore Dollar", symbol: "$"},   
    shp: {name: "Saint Helena Pound", symbol: "£"},   
    sll: {name: "Leone", symbol: "Le"},   
    sos: {name: "Somali Shilling", symbol: "S"},   
    srd: {name: "Surinam Dollar", symbol: "$"},   
    std: {name: "Dobra", symbol: "Db"},   
    svc: {name: "El Salvador Colon", symbol: "$"},   
    syp: {name: "Syrian Pound", symbol: "£"},   
    szl: {name: "Lilangeni", symbol: "L"},   
    thb: {name: "Baht", symbol: "฿"},   
    tjs: {name: "Somoni", symbol: "ЅМ"},   
    tmt: {name: "Manat", symbol: "m"},   
    tnd: {name: "Tunisian Dinar", symbol: "DT"},   
    top: {name: "Pa\"anga", symbol: "DT"},   
    try: {name: "Turkish Lira", symbol: "TL"},   
    ttd: {name: "Trinidad and Tobago Dollar", symbol: "TT$"},   
    tvd: {name: "TVD", symbol: "$"},   
    twd: {name: "New Taiwan Dollar", symbol: "NT$"},   
    tzs: {name: "Tanzanian Shilling", symbol: "Sh"},   
    uah: {name: "Hryvnia", symbol: "₴"},   
    ugx: {name: "Uganda Shilling", symbol: "USh"},   
    usd: {name: "US Dollar", symbol: "$", country: "us"},   
    usn: {name: "US Dollar (Next day}", symbol: "$"},   
    uss: {name: "US Dollar (Same day}", symbol: "$"},   
    uyi: {name: "Uruguay Peso en Unidades Indexadas", symbol: "UYI"},   
    uyu: {name: "Peso Uruguayo", symbol: "$U"},   
    uzs: {name: "Uzbekistan Sum", symbol: "лв"},   
    vef: {name: "Bolivar Fuerte", symbol: "Bs"},   
    vnd: {name: "Dong", symbol: "₫"},   
    vuv: {name: "Vatu", symbol: "VT"},   
    wst: {name: "Tala", symbol: "T"},   
    xaf: {name: "CFA Franc BEAC", symbol: "FCFA", country: "cm"},   
    xag: {name: "Silver", symbol: "XAG"}, 
	xau: {name: "Gold", symbol: "XAU"},   
    xba: {name: "Bond Markets Units European Composite Unit (EURCO}", symbol: "XBA"},   
    xbb: {name: "European Monetary Unit (E.M.U.-6}", symbol: "XBB"},   
    xbc: {name: "European Unit of Account 9(E.U.A.-9}", symbol: "XBC"},   
    xbd: {name: "European Unit of Account 17(E.U.A.-17}", symbol: "XBD"},   
    xcd: {name: "East Caribbean Dollar", symbol: "$", country: "kn"}, 
	xdr: {name: "SDR", symbol: "XDR"},   
    xfu: {name: "UIC-Franc", symbol: "XFU"},   
    xof: {name: "CFA Franc BCEAO", symbol: "CFA", country: "sn"},   
    xpd: {name: "Palladium", symbol: "XPD"},   
    xpf: {name: "CFP Franc", country: "pf", symbol: "Fr"},   
    xpt: {name: "Platinum", symbol: "XPT"},   
    xts: {name: "Codes specifically reserved for testing purposes", symbol: "XTS"},   
    xxx: {name: "The codes assigned for transactions where no currency is involved are:", symbol: "XXX"},   
    yer: {name: "Yemeni Rial", symbol: "﷼"},   
    zar: {name: "Rand", symbol: "R", country: "za"},   
    zmk: {name: "Zambian Kwacha", symbol: "ZK"},   
    zwd: {name:"Zimbabwean dollar", symbol: "Z$"},   
    zwl: {name: "Zimbabwe Dollar", symbol: "$"}
}

CurrencyCodeInfo.GetSymbol = function(code) {
    let item = CurrencyCodeInfo[code.toLowerCase()]
    if (item != null) return item.symbol
    return code.toUpperCase()
}
CurrencyCodeInfo.GetName = function(code) {
    let item = CurrencyCodeInfo[code.toLowerCase()]
    if (item != null) return item.name
    return code.toUpperCase()
}

export default CurrencyCodeInfo