type ErrorCodeApi = Record<string, any>;

var ErrorCode: ErrorCodeApi = {
    SUCCESS: 0,
    NO_METHOD: 101,
    METHOD_NOT_FOUND: 102,
    NO_USER: 201,
    OTHER_LOGINED: 202,
    REPEATED_MESSAGE: 203,
    UNKNOWN: 1001,
    UNKNOWN_CLIENT: 1002,
    REDIS_ERROR: 1003,

    //User
    LOGIN_ERROR: 1101,
    GET_USER_ERROR: 1102,
    GET_USERINFO_ERROR: 1103,
    SAVE_USERINFO_ERROR: 1104,
    GET_USERDATA_ERROR: 1105,
    SAVE_USERDATA_ERROR: 1106,
    GET_RANDOMUSER_ERROR: 1107,
    SAVE_USERSTAR_ERROR: 1108,
    ADD_USERFRIEND_ERROR: 1109,
    DELETE_USERFRIEND_ERROR: 1115,
    SLOT_COIN6_NORECORD: 1110,
    SLOT_COIN6_FAILED: 1111,
    BACK_REWARDADD_FAILED: 1112,
    AD_AFTERINTER_FAILED: 1113,
    AD_TOOMANY_FAILED: 1114,
    COIN_INSUFFICIENT_ERROR: 1116,
    GET_USERINFOLEGION_ERROR: 1117,
    SAVE_USERINFOLEGION_ERROR: 1118,
    LEGIONLOGIN_ERROR: 1119,
    LACKOFEXPERIENCE_ERROR: 1120,
    BOUNDACCOUNT_ERROR: 1121,
    BOUND_ERROR:1122,
    BIND_ERROR:1123,


    //items/content
    GET_USERITEMS_ERROR__: 1201,
    USERDATA_NOT_ENOUGH: 1202,
    COIN_NOT_ENOUGH: 1203,
    AP_NOT_ENOUGH: 1204,
    SHIELD_NOT_ENOUGH: 1205,
    STAR_NOT_ENOUGH: 1206,
    ITEM_NOT_ENOUGH: 1207,
    SPEND_USERDATA_ERROR: 1208,
    SPEND_CONTENT_ERROR: 1209,
    SPEND_CONTENT_ENOUGH_ERROR: 1210,
    ADD_CONTENT_ERROR: 1211,
    USERDATA_SPEND_CONTENT_ERROR: 1212,
    USERDATA_SPEND_CONTENT_ENOUGH_ERROR: 1213,
    USERDATA_ADD_CONTENT_ERROR: 1214,
    ITEM_SPEND_CONTENT_ERROR: 1215,
    ITEM_SPEND_CONTENT_ENOUGH_ERROR: 1216,
    ITEM_ADD_CONTENT_ERROR: 1217,
    CASH_NOT_ENOUGH: 1218,
    CASHTASK_ALREADYGET_ERROR: 1219,
    CASH_NOMETA_ERROR: 1220,
    GET_USERITEMS_ERROR: 1251,
    SAVE_USERITEMS_ERROR: 1252,
    Exp_NOT_ENOUGH: 1256,

    //village
    GET_USERVILLAGE_ERROR: 1301,
    SAVE_USERVILLAGE_ERROR: 1302,
    VILLAGE_LEVELMAX_ERROR: 1303,
    VILLAGE_INVALID_ERROR: 1304,
    VILLAGE_NOTFINISH_ERROR: 1305,
    VILLAGE_NONEWVILLAGE_ERROR: 1306,
    VILLAGE_CANNOTDESTROY_ERROR: 1307,
    VILLAGE_NOCOINS_ERROR: 1308,
    VILLAGE_LEVELLIMITREACHED_ERROR: 1309,
    HOUSE_NOT_FOUND: 1310,

    //MergeMap
    GET_MERGEMAP_ERROR: 4001,
    WAREHOUSE_FULL: 4002,
    WAREHOUSE_MOVE_FAILED: 4003,
    WAREHOUSE_ITEM_NOT_FOUND: 4004,
    REWARD_NOT_FOUND: 4005,
    BOARD_FULL: 4006,
    INVALID_PARAMS: 4007,
    SAVE_MAP_ERROR: 4008,
    MERGE_SAME_CELL: 4009,
    PIECE_NOT_FOUND: 4010,
    PARSE_PIECE_ERROR: 4011,
    MERGE_TYPE_MISMATCH: 4012,
    PIECE_CONFIG_NOT_FOUND: 4013,
    MAX_LEVEL_REACHED: 4014,
    SAVE_DB_ERROR: 4015,
    CANNOT_SELL: 4016,
    NO_REWARD: 4017,
    INVALID_REWARD_CONFIG: 4018,
    ADD_REWARD_FAILED: 4019,
    INVALID_OPERATION_TYPE: 4020,
    NO_UNDO_OPERATION: 4021,
    UNDO_TIMEOUT: 4022,
    CELL_OCCUPIED: 4023,
    GENERATOR_COOLING: 4024,
    ORDER_NOT_FOUND: 4025,
    ORDER_NOT_COMPLETED: 4026,
    ORDER_ALREADY_CLAIMED: 4027,
    ORDERTASK_ERROR: 4028,
    NO_FUNC_OPTIONS: 4029,
    BATCH_OP_FAILED: 4030,
    RESOURCE_NOT_ENOUGH: 4031,
    CANNOT_CUT: 4032,
    MIN_LEVEL_REACHED: 4033,

    //slot
    GET_USERSLOT_ERROR: 1401,
    SLOT_PLAY_ERROR: 1402,
    INTERACTION_ATTACK_NORECORD: 1403,
    INTERACTION_ATTACK_RECORDFAIL: 1404,
    INTERACTION_ATTACK_REMOVERECORDFAIL: 1405,
    INTERACTION_RAID_NORECORD: 1406,
    INTERACTION_RAID_RECORDFAIL: 1407,
    INTERACTION_RAID_REMOVERECORDFAIL: 1408,
    INTERACTION_RAID_GETFRIENDVILLAGEFAIL: 1409,
    SAVE_USERSLOT_ERROR: 1410,
    //dailybonus
    DAILYBONUS_CANNOT_ERROR: 1451,
    //slotmsg
    GET_USERSLOTMSG_ERROR: 1471,
    SLOTMSG_NOPRESENT_ERROR: 1472,
    SAVE_USERSLOTMSG_ERROR: 1473,

    //chat
    GET_CHATS_ERROR: 1501,
    SEND_CHAT_ERROR: 1502,
    GET_LASTCHAT_ERROR: 1503,

    //social
    GET_USERSOCIAL_ERROR: 1601,
    SAVE_USERSOCIAL_ERROR: 1602,
    SEND_ALREADY_ERROR: 1603,
    COLLECT_ALREADY_ERROR: 1604,
    COLLECT_CANNOT_ERROR: 1605,
    SENDALL_FRIENDERROR_ERROR: 1606,

    //shop
    PAYMENT_ADD_ERROR: 1701,
    PAYMENT_NO_META: 1702,
    PAYMENT_VERIFY_ERROR: 1703,
    SHOP_PURCHASE_LIMIT: 1704,

    //tutorial
    GET_USERTUTORIAL_ERROR: 1801,
    SAVE_USERTUTORIAL_ERROR: 1802,
    TUTORIAL_HAVEPASS_ERROR: 1803,
    TUTORIAL_NOMETA_ERROR: 1804,
    TUTORIAL_FINISH_ERROR: 1805,

    //card
    GET_USERCARD_ERROR: 1901,
    SAVE_USERCARD_ERROR: 1902,
    GET_CARD_REWARD_ERROR: 1903,
    CARD_SEND_ERROR: 1904,
    CARD_REWARD_ALREADY: 1905,
    CARD_REWARD_CANNOT: 1906,
    CARD_SENDNOCARD_ERROR: 1907,
    CARD_ADDLIST_ERROR: 1908,
    CARD_WATCHFREE_ERROR: 1909,
    CARD_NOJOKER_ERROR: 1910,
    CARD_FREQUENCY_ERROR: 1911,
    CARD_GET_ACTIVITY_DATA_ERROR: 1912,


    //activity
    GET_USERACTIVITY_ERROR: 2001,
    SAVE_USERACTIVITY_ERROR: 2002,
    ACTIVITY_DROPNOACTIVE_ERROR: 2011,
    //jigsaw
    ACTIVITY_JIGSAW_ALREADYHAS_ERROR: 2021,
    ACTIVITY_JIGSAW_NOTENOUGH_ERROR: 2022,
    // minigame
    MINIGAME_GET_RANK_SCORE_ERROR: 2031,
    MINIGAME_SET_RANK_SCORE_ERROR: 2032,
    MINIGAME_GET_DAILY_FREE_TICKET_ERROR: 2033,
    MINIGAME_SPEND_TICKET_ERROR: 2034,
    MINIGAME_GET_RANK_LIST_ERROR: 2035,
    // minigame-coinhit
    MINIGAME_COINHIT_GET_REWARD_ERROR: 2041,
    // cannon
    CANNON_GET_ACTIVITY_DATA_ERROR: 2051,
    CANNON_SET_ACTIVITY_DATA_ERROR: 2052,
    CANNON_REFRESH_ERROR: 2053,
    CANNON_REFRESH_USE_ERROR: 2054,
    CANNON_REFRESH_FREE_ERROR: 2055,
    CANNON_SHOOT_BALL_ERROR: 2056,
    CANNON_ITEM_NOT_ENOUGH_ERROR: 2057,
    CANNON_GET_REWARD_ERROR: 2058,
    CANNON_SEND_ITEM_ERROR: 2059,
    CANNON_USE_MAGIC_ITEM_ERROR: 20510,
    CANNON_WATCH_AD_GET_BALL_ERROR: 20511,
    CANNON_ADD_BALL_ERROR: 20512,
    CANNON_DROP_BALL_ERROR: 20513,
    CANNON_BUY_BALL_ERROR: 20514,
    CANNON_SHOOT_BALL_BOX_ERROR: 20515,

    //travel
    TRAVEL_GET_ACTIVITY_DATA_ERROR:3001,
    TRAVEL_SET_ACTIVITY_DATA_ERROR:3002,
    TRAVEL_REFRESH_ERROR: 3003,
    TRAVEL_ITEM_NOT_ENOUGH_ERROR: 3004,


    //coupon
    COUPON_BUY_TIME_ERROR:3301,

    // heist
    HEIST_ADD_BUY_COUNT_ERROR: 2061,
    HEIST_FREE_BUY_ERROR: 2062,
    //blackjack
    BLACKJACK_CARDSNUM_ERROR:2066,
    BLACKJACK_BET_NORECORD:2067,
    BLACKJACK_DOUBLE_ERROR:2068,
    BLACKJACK_ALREADY_STARTREWARD:2069,
    //collectFlag
    COLLECTFLAG_ERROR:2071,
    COLLECTFLAG_REWARD_ALREADY:2072,
    COLLECTFLAG_LEVEL_NOTENOUGH:2073,
    COLLECTFLAG_NOT_KING:2074,

    //passport
    PASSPORT_ERROR:2081,
    PASSPORT_REWARD_ALREADY:2082,
    PASSPORT_LEVEL_NOTENOUGH:2083,
    PASSPORT_NOT_BUY:2084,

    //new-passport
    NEW_PASSPORT_ERROR:2085,
    NEW_PASSPORT_NOT_ACTIVE:2086,
    NEW_PASSPORT_META_NOT_FOUND:2087,
    NEW_PASSPORT_TASK_NOT_ACTIVE:2088,

    //activity-merge（活动任务奖励）
    ACTIVITY_MERGE_ERROR: 2091,
    ACTIVITY_MERGE_INVALID_PARAMS: 2092,
    ACTIVITY_MERGE_NOT_ACTIVE: 2093,
    ACTIVITY_MERGE_TASK_NOT_FOUND: 2094,
    ACTIVITY_MERGE_TASK_CONFIG_ERROR: 2095,
    ACTIVITY_MERGE_REWARD_ALREADY: 2096,
    ACTIVITY_MERGE_PROGRESS_NOT_ENOUGH: 2097,
    ACTIVITY_MERGE_REWARD_CONFIG_ERROR: 2098,

    //dailyTasks 餐厅任务
    DAILYTASKS_ERROR: 2107,
    DAILYTASKS_NOT_ACTIVE: 2108,
    DAILYTASKS_META_NOT_FOUND: 2109,
    DAILYTASKS_DAY_NOT_UNLOCK: 2110,
    DAILYTASKS_REWARD_ALREADY: 2111,
    DAILYTASKS_NOT_COMPLETE: 2112,
    DAILYTASKS_TARGET_UNKNOWN: 2113,
    DAILYTASKS_INVALID_STEP: 2114,

    //globalTour 环球之旅
    GLOBAL_TOUR_ERROR: 2120,
    GLOBAL_TOUR_NOT_ACTIVE: 2121,
    GLOBAL_TOUR_INVALID_PARAMS: 2122,
    GLOBAL_TOUR_CHECKPOINT_NOT_FOUND: 2123,
    GLOBAL_TOUR_REWARD_ALREADY: 2124,
    GLOBAL_TOUR_PROGRESS_NOT_ENOUGH: 2125,
    GLOBAL_TOUR_NO_SLOTS: 2126,
    GLOBAL_TOUR_GRAND_ALREADY: 2127,

    //task
    GET_USERTASK_ERROR: 2101,
    TASK_NOTCOMPLETE_ERROR: 2102,
    TASK_NOTTODAY_ERROR: 2103,
    TASK_COUNT_ERROR: 2104,
    TASK_ALREADYREWARD_ERROR: 2105,
    TASK_CLIENTCANT_ERROR: 2106,

    //sign
    GET_USERTSIGN_ERROR: 2201,
    SAVE_USERTSIGN_ERROR: 2202,
    SIGN_SIGNWEEK_ERROR: 2203,
    SIGN_GETMONTH_ERROR: 2204,

    //record
    GET_USERRECORD_ERROR: 2301,
    SAVE_USERRECORD_ERROR: 2302,

    //status
    GET_USERSTATUS_ERROR: 2401,
    SAVE_USERSTATUS_ERROR: 2402,
    VIP_GETTIME_ERROR: 2403,
    LEVELBONUS_ALREADY_REWARD: 2404,
    LEVELBONUS_MAPID_LESS: 2405,
    LEVELBONUS_NOTBUY_ERROR: 2406,

    //legion
    GET_LEGION_ERROR:2601,
    CDING:2602,
    LEGION_ERROR:2603,
    SEARCH_LEGION_ERROR:2604,
    ADD_LEGION_ERROR:2605,
    MODIFY_LEGION_ERROR:2606,
    JOIN_LEGION_ERROR:2607,
    OUT_LEGION_ERROR:2608,
    SIGN_LEGION_ERROR:2609,
    NEWS_LEGION_ERROR:2610,
    HELP_LEGION_ERROR:2611,


    //broadcast
    GET_BROADCAST_ERROR:2801,


    //balloon
    SET_BALLOON_ERROR:2701,
}


ErrorCode.muteError = function(code) {
    switch(code) {
        /*case ErrorCode.USERDATA_NOT_ENOUGH:
        case ErrorCode.COIN_NOT_ENOUGH:
        case ErrorCode.AP_NOT_ENOUGH:
        {
            AppGame.instance.reqUserData()
            return true
        }*/
        case ErrorCode.BIND_ERROR: {return true}
        case ErrorCode.BOUNDACCOUNT_ERROR: {return true}
        case ErrorCode.PAYMENT_VERIFY_ERROR: {return true}
        default:break
    }
    return false
}

ErrorCode.tipError = function(code) {
    switch(code) {
        /*case ErrorCode.USERDATA_NOT_ENOUGH:
        case ErrorCode.COIN_NOT_ENOUGH:
        case ErrorCode.AP_NOT_ENOUGH:
        {
            AppGame.instance.reqUserData()
            return true
        }*/
        case ErrorCode.AD_TOOMANY_FAILED: {return true}
        default:break
    }
    return false
}
ErrorCode.ShowToast = function(code) {
    console.log("errorCode =",code);
    
    switch(code) {
        /*case ErrorCode.USERDATA_NOT_ENOUGH:
        case ErrorCode.COIN_NOT_ENOUGH:
        case ErrorCode.AP_NOT_ENOUGH:
        {
            AppGame.instance.reqUserData()
            return true
        }*/
        case ErrorCode.BOUNDACCOUNT_ERROR: 
        case ErrorCode.BOUND_ERROR: 
        case ErrorCode.BIND_ERROR: 
            UIRoot.instance.ShowToast(GameKit.i18n.t("ErrorCode"+code))
            break
        case ErrorCode.AD_TOOMANY_FAILED: {return true}
        default:break
    }
}


global.ErrorCode = ErrorCode

export default ErrorCode
